application: wild-karma
version: 1-0-0
runtime: python27
threadsafe: true
api_version: 1

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^\.idea$
- ^(.*/)?.*\.iml$
- ^node_modules$

handlers:
- url: /(.+)
  static_files: \1
  upload: (.*)

- url: /
  static_files: index.html
  upload: index.html
